version: "3.3"
services:
  db:
    image: "mysql:5.7.37-oracle"
    volumes:
      - "./.mysql-data/db:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=emlak
      - MYSQL_DATABASE=emlak
    restart: "always"
  web:
    build: .
    volumes:
      - "/root/orient/uploads:/usr/src/app/uploads"
    ports:
      - "49901:80"
      - "49902:443"
    restart: "always"
